# SwiftLint configuration for TrysteroSwift

# Paths to include
included:
  - Sources
  - Tests
  - Examples

# Paths to exclude
excluded:
  - .build
  - Package.swift
  - Tests/Interop
  - Examples/Chat/.build
  - "**/.build"

# Rules
disabled_rules:
  - trailing_comma # Allow trailing commas
  - todo # Allow TODO comments
  - line_length # Disabled for now, can enable with custom length

opt_in_rules:
  - empty_count
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_string
  - first_where
  - last_where
  - literal_expression_end_indentation
  - multiline_parameters
  - prefer_zero_over_explicit_init
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument

# Rule configuration
force_cast: warning
force_try: warning

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - to

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3

# Custom rules
custom_rules:
  no_print_in_library:
    name: "No print statements in library code"
    regex: '^\s*print\('
    match_kinds:
      - identifier
    message: "Use proper logging instead of print statements"
    severity: warning
    excluded:
      - Tests
      - Examples
      - Sources # Temporarily exclude Sources during development