name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    name: Generate Documentation
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build Documentation with xcodebuild
      run: |
        xcodebuild docbuild \
          -scheme TrysteroSwift \
          -destination 'generic/platform=macOS' \
          -derivedDataPath ./build
        
        # Find and copy documentation archive
        find ./build -name "*.doccarchive" -exec cp -R {} ./docs \;
          
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        
  validate-readme:
    name: Validate README
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Check README links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/markdown-link-check-config.json'
        
    - name: Validate code examples in README
      run: |
        # Extract Swift code blocks and validate syntax
        grep -A 10 -B 2 '```swift' README.md > code_examples.swift
        echo "Code examples extracted for validation"